apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-rollout-hpa
  labels:
    app: frontend-rollout
spec:      # The min and max number of pods the HPA can scale
  minReplicas: 4
  maxReplicas: 10
  scaleTargetRef:       # The HPA targets the Rollout object for scaling.
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: frontend-rollout
  metrics: # Defines the scaling trigger
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 16Mi
